### ISSUE TITLE
too many distance function evaluations?

### ISSUE THREAD

**Issue by tomlue** [barneygovan/lsh-scala#1]
in LSH.scala you have the lines

```
val results = for {
      (key, i) <- calculateHashes(point).zipWithIndex
        items = tables(i).get(key)
      (label, _, otherPoint) <- items  if isLabelNew(label, labelSet)
    } yield (label, distanceFunction(point, otherPoint))
```

I think this ends up evaluating the distance function on any point that collides in at least one lsh table.  
When the distance function evaluation is slow, I think you get a significant speed up if you require multiple collisions. Something like:

```
  def query(point: INDArray,
            maxItems: Int = 25,
            distanceFunction: (INDArray,INDArray) => Double = euclideanDistance):
            IndexedSeq[(String, Double)] = {


    val keys      = calculateHashes(point)
    val analogues: Iterable[(String,Double)] = keys.zip(tables)
      .flatMap( kt => kt._2.get(kt._1)).map(x => (x._1,x._3))
      .groupBy(x => x).map( x => (x._1,x._2.length))
      .filter(_._2 > CHOOSE_NUMBER_OF_COLLISION)
      .keys
      .map(x => (x._1,distanceFunction(point,x._2)))

    val heap = new mutable.PriorityQueue[(String, Double)]()(Ordering.by(_._2))
    heap ++= analogues
    heap.take(maxItems).toIndexedSeq
  }
```

Where a large requirement for CHOOSE_NUMBER_OF_COLLISION will potentially miss nearby points but be much faster, and a small requirement will be slower but miss less points.

**Comment by barneygovan** [comment]
If you want to improve the performance by reducing the number of candidates selected, you can reduce the number of tables.

The point of the tables is to reduce the "approximate" nature of this approach, by having multiple overlapping random projections (and catch the candidates that lie just outside the bucket which are therefore similar candidates).  It's possible that your stated approach might offer a middle ground between the "fewer tables" and the "more tables" scenarios, but I think reducing/increasing the number of tables is simpler and easier to reason about.
